/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.sgd.vueControleur;

import com.mongodb.client.MapReduceIterable;
import fr.ufrsciencestech.sgd.modele.*;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.apache.commons.lang3.math.NumberUtils;

/**
 *
 * @author tf872254
 */
public class RechercheUtilisateur extends javax.swing.JFrame implements Observer{

    private Modele m;
    private boolean[] criteres = new boolean[6];
    private String[] conditions = new String[5];
    private String avis = "", jeu = "", pseudo = "tibo", mail = "tibo@tibolebg.gouv";
    private float note = -1;
    
    /**
     * Creates new form RechercheUtilisateur
     * @param mod
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public RechercheUtilisateur(Modele mod) {
        initComponents();
        
        criteres[0] = true;
        Arrays.fill(conditions, "ou");
        
        this.m  = mod;        
        this.m.addObserver(this);
        
        this.jList1.clearSelection();
        
        this.setVisible(true);
        
        String text = "";
        
        MapReduceIterable mri = m.getBD().mapReduce();
        
        while(mri.iterator().hasNext()){
            text += mri.iterator().next().toString() + "\n";        
        }
        
        this.jTextArea1.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jComboBox11 = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jComboBox12 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridLayout(6, 0, 0, 5));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rechercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox7.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox7, 0, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox7)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel9.add(jCheckBox2, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("et");
        jRadioButton3.setEnabled(false);
        jRadioButton3.setMaximumSize(new java.awt.Dimension(43, 23));
        jRadioButton3.setMinimumSize(new java.awt.Dimension(43, 23));
        jRadioButton3.setPreferredSize(new java.awt.Dimension(43, 23));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel9.add(jRadioButton3, gridBagConstraints);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("ou");
        jRadioButton4.setEnabled(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel9.add(jRadioButton4, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel9.add(jComboBox2, gridBagConstraints);

        jTextField2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        jPanel9.add(jTextField2, gridBagConstraints);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox8.setEnabled(false);
        jPanel9.add(jComboBox8, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel10.add(jCheckBox3, gridBagConstraints);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("et");
        jRadioButton5.setEnabled(false);
        jRadioButton5.setMaximumSize(new java.awt.Dimension(43, 23));
        jRadioButton5.setMinimumSize(new java.awt.Dimension(43, 23));
        jRadioButton5.setPreferredSize(new java.awt.Dimension(43, 23));
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel10.add(jRadioButton5, gridBagConstraints);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("ou");
        jRadioButton6.setEnabled(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel10.add(jRadioButton6, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel10.add(jComboBox3, gridBagConstraints);

        jTextField3.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        jPanel10.add(jTextField3, gridBagConstraints);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox9.setEnabled(false);
        jPanel10.add(jComboBox9, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel11.add(jCheckBox4, gridBagConstraints);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("et");
        jRadioButton7.setEnabled(false);
        jRadioButton7.setMaximumSize(new java.awt.Dimension(43, 23));
        jRadioButton7.setMinimumSize(new java.awt.Dimension(43, 23));
        jRadioButton7.setPreferredSize(new java.awt.Dimension(43, 23));
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel11.add(jRadioButton7, gridBagConstraints);

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("ou");
        jRadioButton8.setEnabled(false);
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel11.add(jRadioButton8, gridBagConstraints);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox4.setEnabled(false);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel11.add(jComboBox4, gridBagConstraints);

        jTextField4.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        jPanel11.add(jTextField4, gridBagConstraints);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox10.setEnabled(false);
        jPanel11.add(jComboBox10, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel12.add(jCheckBox5, gridBagConstraints);

        buttonGroup4.add(jRadioButton9);
        jRadioButton9.setText("et");
        jRadioButton9.setEnabled(false);
        jRadioButton9.setMaximumSize(new java.awt.Dimension(43, 23));
        jRadioButton9.setMinimumSize(new java.awt.Dimension(43, 23));
        jRadioButton9.setPreferredSize(new java.awt.Dimension(43, 23));
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel12.add(jRadioButton9, gridBagConstraints);

        buttonGroup4.add(jRadioButton10);
        jRadioButton10.setText("ou");
        jRadioButton10.setEnabled(false);
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel12.add(jRadioButton10, gridBagConstraints);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox5.setEnabled(false);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel12.add(jComboBox5, gridBagConstraints);

        jTextField5.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        jPanel12.add(jTextField5, gridBagConstraints);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox11.setEnabled(false);
        jPanel12.add(jComboBox11, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridBagLayout());

        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel13.add(jCheckBox6, gridBagConstraints);

        buttonGroup5.add(jRadioButton11);
        jRadioButton11.setText("et");
        jRadioButton11.setEnabled(false);
        jRadioButton11.setMaximumSize(new java.awt.Dimension(43, 23));
        jRadioButton11.setMinimumSize(new java.awt.Dimension(43, 23));
        jRadioButton11.setPreferredSize(new java.awt.Dimension(43, 23));
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel13.add(jRadioButton11, gridBagConstraints);

        buttonGroup5.add(jRadioButton12);
        jRadioButton12.setText("ou");
        jRadioButton12.setEnabled(false);
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel13.add(jRadioButton12, gridBagConstraints);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "categorie", "pegi", "date de parution", "disponibilite", "serie", "note >", "note <", "note =" }));
        jComboBox6.setEnabled(false);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel13.add(jComboBox6, gridBagConstraints);

        jTextField6.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 12);
        jPanel13.add(jTextField6, gridBagConstraints);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rts", "multijoueur", "fps", "moba", "enfant", "adulte", "p2w", "meuporg", "solo", "aventure" }));
        jComboBox12.setEnabled(false);
        jPanel13.add(jComboBox12, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel13);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Déposer un avis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        ArrayList<String> listeCategorie = new ArrayList();
        ArrayList<String> listeContenu = new ArrayList();
        String[] tabTemp;
        
        for(int i = 0; i < criteres.length; i++){
            if(criteres[i]){
                tabTemp = this.recuperationValeurs(i);
                listeCategorie.add(tabTemp[0]);
                listeContenu.add(tabTemp[1]);
            }
        }        
        
        m.preparerRequete(criteres, conditions, listeCategorie, listeContenu);
    }//GEN-LAST:event_jButton2ActionPerformed

    private String[] recuperationValeurs(int i){
        String[] retour = new String[2];
        
        switch(i){
            case 0:
                retour[0] = this.jComboBox1.getSelectedItem().toString();
                 if(this.jComboBox1.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox7.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField1.getText();
                }
                break;
            case 1:
                retour[0] = this.jComboBox2.getSelectedItem().toString();
                 if(this.jComboBox2.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox8.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField2.getText();
                }
                break;
            case 2:
                retour[0] = this.jComboBox3.getSelectedItem().toString();
                 if(this.jComboBox3.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox9.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField3.getText();
                }
                break;
            case 3:
                retour[0] = this.jComboBox4.getSelectedItem().toString();
                 if(this.jComboBox4.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox10.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField4.getText();
                }
                break;
            case 4:
                retour[0] = this.jComboBox5.getSelectedItem().toString();
                 if(this.jComboBox5.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox11.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField5.getText();
                }
                break;
            case 5:
                retour[0] = this.jComboBox6.getSelectedItem().toString();
                 if(this.jComboBox6.getSelectedItem().equals("categorie")){
                    retour[1] = this.jComboBox12.getSelectedItem().toString();
                } else {
                    retour[1] = this.jTextField6.getText();
                }
                break;
        }
        
        return retour;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        
        ArrayList<String> l = this.m.getListeJeux();
        String[] s = l.toArray(new String[l.size()]);
        this.jList1.setListData(s);
        
        this.jTextArea1.setText(m.getZoneDeTexte());
        
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(this.jComboBox1.getSelectedItem().equals("categorie")){
            this.jComboBox7.setEnabled(true);
            this.jTextField1.setEnabled(false);
        }
        else{
            this.jComboBox7.setEnabled(false);
            this.jTextField1.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(this.jCheckBox2.isSelected()){
            this.jRadioButton3.setEnabled(true);
            this.jRadioButton4.setEnabled(true);
            this.jComboBox2.setEnabled(true);
            if(this.jComboBox2.getSelectedItem().equals("categorie")){
                this.jComboBox8.setEnabled(true);
                this.jTextField2.setEnabled(false);
            }
            else{
                this.jComboBox8.setEnabled(false);
                this.jTextField2.setEnabled(true);
            }
            this.criteres[1] = true;
        } else{
            this.jRadioButton3.setEnabled(false);
            this.jRadioButton4.setEnabled(false);
            this.jComboBox2.setEnabled(false);
            this.jTextField2.setEnabled(false);
            this.jComboBox8.setEnabled(false);
            this.criteres[1] = false;
        }        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(this.jCheckBox3.isSelected()){
            this.jRadioButton5.setEnabled(true);
            this.jRadioButton6.setEnabled(true);
            this.jComboBox3.setEnabled(true);
            if(this.jComboBox3.getSelectedItem().equals("categorie")){
                this.jComboBox9.setEnabled(true);
                this.jTextField3.setEnabled(false);
            }
            else{
                this.jComboBox9.setEnabled(false);
                this.jTextField3.setEnabled(true);
            }
            this.criteres[2] = true;
        } else{
            this.jRadioButton5.setEnabled(false);
            this.jRadioButton6.setEnabled(false);
            this.jComboBox3.setEnabled(false);
            this.jTextField3.setEnabled(false);
            this.jComboBox9.setEnabled(false);  
            this.criteres[2] = false;      
        }        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(this.jCheckBox4.isSelected()){
            this.jRadioButton7.setEnabled(true);
            this.jRadioButton8.setEnabled(true);
            this.jComboBox4.setEnabled(true);
            if(this.jComboBox4.getSelectedItem().equals("categorie")){
                this.jComboBox10.setEnabled(true);
                this.jTextField4.setEnabled(false);
            }
            else{
                this.jComboBox10.setEnabled(false);
                this.jTextField4.setEnabled(true);
            }
            this.criteres[3] = true;
        } else{
            this.jRadioButton7.setEnabled(false);
            this.jRadioButton8.setEnabled(false);
            this.jComboBox4.setEnabled(false);
            this.jTextField4.setEnabled(false);
            this.jComboBox10.setEnabled(false);    
            this.criteres[3] = false;      
        }  
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(this.jCheckBox5.isSelected()){
            this.jRadioButton9.setEnabled(true);
            this.jRadioButton10.setEnabled(true);
            this.jComboBox5.setEnabled(true);
            if(this.jComboBox5.getSelectedItem().equals("categorie")){
                this.jComboBox11.setEnabled(true);
                this.jTextField5.setEnabled(false);
            }
            else{
                this.jComboBox11.setEnabled(false);
                this.jTextField5.setEnabled(true);
            }
            this.criteres[4] = true;
        } else{
            this.jRadioButton9.setEnabled(false);
            this.jRadioButton10.setEnabled(false);
            this.jComboBox5.setEnabled(false);
            this.jTextField5.setEnabled(false);
            this.jComboBox11.setEnabled(false);   
            this.criteres[4] = false;      
        }  
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if(this.jCheckBox6.isSelected()){
            this.jRadioButton11.setEnabled(true);
            this.jRadioButton12.setEnabled(true);
            this.jComboBox6.setEnabled(true);
            if(this.jComboBox6.getSelectedItem().equals("categorie")){
                this.jComboBox12.setEnabled(true);
                this.jTextField6.setEnabled(false);
            }
            else{
                this.jComboBox12.setEnabled(false);
                this.jTextField6.setEnabled(true);
            }
            this.criteres[5] = true;
        } else{
            this.jRadioButton11.setEnabled(false);
            this.jRadioButton12.setEnabled(false);
            this.jComboBox6.setEnabled(false);
            this.jTextField6.setEnabled(false);
            this.jComboBox12.setEnabled(false);  
            this.criteres[5] = false;      
        }  
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        jeu = this.jList1.getSelectedValue();
        m.afficherJeu(jeu);        
    }//GEN-LAST:event_jList1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(this.jComboBox2.getSelectedItem().equals("categorie")){
            this.jComboBox8.setEnabled(true);
            this.jTextField2.setEnabled(false);
        }
        else{
            this.jComboBox8.setEnabled(false);
            this.jTextField2.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(this.jComboBox3.getSelectedItem().equals("categorie")){
            this.jComboBox9.setEnabled(true);
            this.jTextField3.setEnabled(false);
        }
        else{
            this.jComboBox9.setEnabled(false);
            this.jTextField3.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(this.jComboBox4.getSelectedItem().equals("categorie")){
            this.jComboBox10.setEnabled(true);
            this.jTextField4.setEnabled(false);
        }
        else{
            this.jComboBox10.setEnabled(false);
            this.jTextField4.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(this.jComboBox5.getSelectedItem().equals("categorie")){
            this.jComboBox11.setEnabled(true);
            this.jTextField5.setEnabled(false);
        }
        else{
            this.jComboBox11.setEnabled(false);
            this.jTextField5.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        if(this.jComboBox6.getSelectedItem().equals("categorie")){
            this.jComboBox12.setEnabled(true);
            this.jTextField6.setEnabled(false);
        }
        else{
            this.jComboBox12.setEnabled(false);
            this.jTextField6.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jeu.equals("")){
            JOptionPane.showMessageDialog(this, "Pas de jeu sélectionné");
        }else{
            JPanel jp = new JPanel();
            
            JLabel jl = new JLabel();
            jl.setText("Note:");
            JTextField jnote = new JTextField(10);
            JLabel jl2 = new JLabel();
            jl2.setText("Avis:");
            JTextArea javis = new JTextArea(30,30);
            
            
            jp.add(jl);
            jp.add(jnote);
            jp.add(jl2);
            jp.add(javis);
            
            int result = JOptionPane.showConfirmDialog(null, jp, "Ajout avis", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                this.note = (NumberUtils.isNumber(jnote.getText()))? Float.parseFloat(jnote.getText()) : -1;
                this.avis = javis.getText();
            }
            
            if(note != -1){
                m.ajouterAvis(jeu, note, avis, pseudo, mail);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        conditions[1] = "et";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        conditions[2] = "et";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        conditions[3] = "et";
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        conditions[4] = "et";
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        conditions[5] = "et";
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        conditions[1] = "ou";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        conditions[2] = "ou";
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        conditions[3] = "ou";
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        conditions[4] = "ou";
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        conditions[5] = "ou";
    }//GEN-LAST:event_jRadioButton12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
